musicsite/lemni/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
from .views import ArtistsView, ArtistDetail, main, SongsView, ClipsView, LemniLoginView, SongDetail, \
    profile, RegistrationUserView, RegistrationDoneView, user_activate, AlbumsView, AlbumDetail

# from .views import ArtistSongsView

app_name = 'lemni'

urlpatterns = [
    path('', main, name='main'),
    path('accounts/login/', LemniLoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='lemni:main'), name='logout'),
    path('accounts/register/', RegistrationUserView.as_view(), name='registration'),
    path('accounts/register/activate/<str:sign>', user_activate, name='registration_activate'),
    path('accounts/register/done', RegistrationDoneView.as_view(), name='registration_done'),
    path('accounts/profile/', profile, name='profile'),
    path('artists/', ArtistsView.as_view(), name='artists_list'),
    # path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$' , ArtistDetail.as_view(), name='artist_detail'),
    path('artists/<slug:slug>/', ArtistDetail.as_view(), name='artist_detail'),
    path('songs/', SongsView.as_view(), name='songs_list'),
    path('songs/<slug:slug>/', SongDetail.as_view(), name='song_detail'),
    path('albums/', AlbumsView.as_view(), name='albums_list'),
    path('albums/<slug:slug>/', AlbumDetail.as_view(), name='album_detail'),
    # path('songs/<id>/<slug:slug>/', ArtistSongsView.as_view(), name='artist_songs_list'),
    # path('songs/<id>/<slug:slug>/', ArtistSongsView.as_view(), name='artist_songs_list'),
    path('clips/', ClipsView.as_view(), name='clips_list'),
]

musicsite/musicsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lemni.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

musicsite/lemni/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=15)
    slug = models.SlugField(max_length=15, db_index=True, unique=True)
    draft = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Musical Genre'
        verbose_name_plural = 'Musical Genres'


class Clip(models.Model):
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=500)  # There will be a link from YouTube
    slug = models.SlugField(max_length=230, db_index=True, unique=True, primary_key=True)

    draft = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Clip'
        verbose_name_plural = 'Clips'


class Artist(models.Model):
    alias = models.CharField(max_length=25)
    slug = models.SlugField(max_length=25, db_index=True, unique=True, primary_key=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    genres = models.ManyToManyField(Genre)
    birthday = models.DateField()
    photo = models.ImageField(upload_to='artists')
    description = models.TextField()
    clips = models.ManyToManyField(Clip, blank=True)
    draft = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return self.alias

    class Meta:
        verbose_name = 'Artist'
        verbose_name_plural = 'Artists'
        ordering = ['alias']

    def get_absolute_url(self):
        return reverse('lemni:artist_detail', args=[self.slug])


class Album(models.Model):
    name = models.CharField(max_length=55)
    slug = models.SlugField(max_length=60, db_index=True, unique=True, primary_key=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='al_covers', blank=True)
    release_date = models.DateField(blank=True)

    class Meta:
        verbose_name = 'Album'
        verbose_name_plural = 'Albums'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lemni:album_detail', args=[self.slug])


class Song(models.Model):
    name = models.CharField(max_length=55)
    slug = models.SlugField(max_length=100, db_index=True, unique=True, primary_key=True)
    artist = models.ManyToManyField(Artist)
    album = models.ForeignKey(Album, on_delete=models.RESTRICT, default=1)
    feature = models.ManyToManyField(Artist, related_name='feature', blank=True)
    audio_file = models.FileField(default='')
    cover = models.ImageField(upload_to='covers')
    release_date = models.DateField()
    description = models.TextField()
    lyrics = models.CharField(max_length=100)  # There will be a link to Genius
    genre = models.ManyToManyField(Genre)
    draft = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Song'
        verbose_name_plural = 'Songs'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('lemni:song_detail', args=[self.slug])


class MyUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Passed activation')
    send_messages = models.BooleanField(default=True, verbose_name='Receiving of email notifications')

    class Meta(AbstractUser.Meta):
        pass

musicsite/lemni/forms.py
import unicodedata

from django import forms
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.forms import UsernameField, AuthenticationForm
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX, identify_hasher,
)
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMultiAlternatives
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.text import capfirst
from django.utils.translation import gettext, gettext_lazy as _

from .apps import user_registered
from .models import MyUser

UserModel = get_user_model()

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'placeholder': 'password'}),
    )


class RegistrationForm(forms.ModelForm):
    username = UsernameField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password'}), help_text=password_validation.password_validators_help_text_html)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password again'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'first_name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'last_name'}))




    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError ('Entered passwords are different', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegistrationForm, instance=user)
        return user
    class Meta:
        model = MyUser
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages']

musicsite/lemni/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.signing import BadSignature
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.base import View, TemplateView

from .forms import LoginForm, RegistrationForm
from .models import Artist, Genre, Song, Clip, MyUser, Album
from .utilities import signer

import requests


def main(request):
    return render(request, 'lemni/base.html')


class ArtistsView(View):

    def get(self, request):
        artists = Artist.objects.all()
        context = {'artists': artists}
        return render(request, 'lemni/artists_list.html', context)


class ArtistDetail(View):

    def get(self, request, slug):
        # artist = Artist.objects.all() # filter by slug
        artist = get_object_or_404(Artist, slug=slug)
        songs = Song.objects.filter(artist__slug=slug)
        albums = Album.objects.filter(artist__slug=slug)
        context = {'artist': artist, 'songs': songs, 'albums': albums}
        return render(request, 'lemni/artist_detail.html', context)

# <!-- {% if album.name != 'None' %} -->
# <!-- {% endif %} -->


class SongsView(View):

    def get(self, request):
        songs = Song.objects.all()
        context = {'songs': songs}
        return render(request, 'lemni/songs_list.html', context)


class SongDetail(View):

    def get(self, request, slug):
        song = get_object_or_404(Song, slug=slug)
        # artist = Artist.objects.get(pk = 1)
        # artist = Artist.objects.filter(song__slug=slug)
        artist = Artist.objects.get(song__slug=slug)
        # feature = Song.objects.get(slug=slug).feature
        # feature = song.feature.filter(song__slug=slug)
        features = song.feature.all()
        # artist = Artist.objects.get(pk=1)
        # genres = Genre.objects.filter(pk=slug[0])
        genres = Genre.objects.filter(song__slug=slug)
        context = {'song': song, 'artist': artist, 'genres': genres,
                   'features': features
                   }
        print(features)
        return render(request, 'lemni/song_detail.html', context)


class AlbumsView(View):

    def get(self, request):
        albums = Album.objects.all()
        # artists = Artist.objects.filter(album__song=)
        context = {'albums': albums}
        return render(request, 'lemni/albums_list.html', context)


class AlbumDetail(View):
    def get(self, request, slug):
        album = Album.objects.get(slug=slug)
        songs = Song.objects.filter(album_id=slug)
        # features = songs.feature.all()
        artist = Artist.objects.filter(slug='Gunna')
        context = {'album': album, 'songs': songs, 'artist': artist,
                   # 'features': features
                   }
        print(songs)

        # for song in songs:
        #     print(song.feature)
        return render(request, 'lemni/album_detail.html', context)


'''
class ArtistSongsView(View):
    def get(self, request, id, slug):
        # if id:
        #     songs = Song.objects.filter(artist=id)
        # else:
        #     songs = Song.objects.all()
        artist = Artist.objects.filter(id=id)
        # songs = Song.objects.filter(artist_slug=artist_slug)
        # songs = Song.objects.filter(slug__startswith="1")
        # songs = Song.objects.filter(slug__startswith= "Artist.pk")
        # songs = Artist.objects.get(id=4).song_set.all()
        # songs = Song.objects.filter(slug="1-praise-lord")
        # songs = Song.objects.filter(slug= "1" + "-praise-lord")
        songs = Song.objects.filter(artist__slug=slug)
        # songs = Song.objects.filter(slug__startswith='1')
        # songs = Song.objects.filter(slug__startswith='1')
        # songs = Song.objects.all()


        # songs = get_object_or_404(Song) Pay attention to it!!!


        # songs = Song.objects.all()
                # if artist_slug:
        #     artist = get_object_or_404(Artist, slug=artist_slug)
        #     songs = Song.objects.filter(artist=artist.id)
        #     # print('HIIIII')
        context = {'songs': songs}
        return render(request, 'lemni/songs_list.html', context)
'''


class ClipsView(View):
    def get(self, request):
        clips = Clip.objects.all()
        context = {'clips': clips}
        return render(request, 'lemni/clips_list.html', context)


class LemniLoginView(LoginView):
    template_name = 'user/login.html'
    # redirect_field_name = ''
    authentication_form = LoginForm


@login_required
def profile(request):
    return render(request, 'user/profile.html')


class RegistrationUserView(CreateView):
    model = MyUser
    template_name = 'user/registration.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('lemni:registration_done')


class RegistrationDoneView(TemplateView):
    template_name = 'user/registration_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'user/bad_signature.html')
    user = get_object_or_404(MyUser, username=username)
    if user.is_activated:
        template = 'user/user_is_activated.html'
    else:
        template = 'user/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

musicsite/lemni/templates/lemni/album_detail.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}{{ album.name }}{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/album_detail.css'%}">{% endblock %}
{% block content %}
    <div class='item'>
        <img class='photo' src="{{ album.cover.url }}" alt="">
        <div class="description">
            <h1 class='album_name'><span class='label'>Title: </span> {{ album.name }}</h1>
            <div class="artist"><span class='label'>Artist: </span><a href='{{ album.artist.get_absolute_url }}'>{{ album.artist }}</a></div>
            <div class="release_date"><span class="label">Release date: </span> {{ album.release_date }}</div>
        </div>
        
    </div>
    
    {% for song in songs %}
    <div class="song">
        
            <!-- <img src="{% static 'sound/play.svg'%}" alt="" class='play'> -->
            {{ album.artist }}  feat. {{ song.feature }} — {{song.name}}<br>
            <audio controls style="width: 600px;">
                
                <source src="{{ song.audio_file.url }}" type="audio/ogg" />
                <source src="{{ song.audio_file.url }}" type="audio/mpeg" />
                <source src="{{ song.audio_file.url }}" type="audio/wav" />
              Your browser does not support the audio element.
            </audio>

            
        
    </div>
    {% endfor %}
    
<!--    <script src="https://apps.elfsight.com/p/platform.js" defer></script>-->
<!--    <div class="elfsight-app-48e9b13b-f05e-4be6-8bae-2ea8d1e34174"></div>-->
    <!-- {% if album.slug == 'g-eazy-scary-nights' %}
    {% endif %} -->

    <!-- <script src="https://apps.elfsight.com/p/platform.js" defer></script>
    <div class="elfsight-app-48e9b13b-f05e-4be6-8bae-2ea8d1e34174"></div> -->



   
    
    

{% endblock %}

musicsite/lemni/templates/lemni/albums_list.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}Albums{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/albums_list.css'%}">{% endblock %}
{% block content %}
<div class='albums_list'>
    <h1 class='title'>Albums</h1>
    <!-- <input type="text" placeholder="Search..."> -->
    {% for album in albums %}
        {% if album.name != 'None' %}
        <div class='album'>
            <a class='album_link' href="{{ album.get_absolute_url }}">
                <img class='cover' src="{{ album.cover.url }}" alt="">
                <span class='album_name'>{{ album.name }}</span>
                
            </a> 
        </div>   
        <!-- <div class='artist-alias'>{{ artist.alias }}</div> -->
        {% endif %}


    {% endfor %}
</div>
{% endblock %}

musicsite/lemni/templates/lemni/artist_detail.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}{{ artist.alias }}{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/artist_detail.css'%}">{% endblock %}
{% block content %}
<div class='item'>
    <img class='photo' src="{{ artist.photo.url }}" alt="">
    <div class="description">
        <h1 class='artist-alias'><span class='label'>Alias:</span> {{ artist.alias }}</h1>
        <div class="artist-real-name"><span class='label'>Original name:</span> {{ artist.first_name }} {{ artist.last_name }}</div>
        <div class="birthday"><span class="label">Birthday: </span> {{ artist.birthday }}</div>
        <div class="info"><span class='label'>Info: </span>{{ artist.description }}</div>
<!--        <div class="songs"><a href="#" class="songs-link">Songs</a></div>-->
    </div>
    
</div>

<!--<div class="songs">-->
<!--    {% for song in songs %}-->
<!--    &lt;!&ndash; <a class='song_link' href="{{ song.get_absolute_url }}">-->
<!--        <img class='song_cover' src="{{ song.cover.url }}" alt="">-->
<!--        <div class='song'>-->
<!--            <div class='song_name'>{{ song.name }}</div>-->
<!--            -->
<!--        </div> &ndash;&gt;-->
<!--        <div class='song'>-->
<!--            <a class='song_link' href="{{ song.get_absolute_url }}">-->
<!--                <img class='song_cover' src="{{ song.cover.url }}" alt="">-->
<!--                <span class='artist-alias'>{{ song.name }}</span>-->
<!--            </a> -->
<!--        </div> -->
<!--    </a> -->
<!--    {% endfor %}-->
<!--</div>-->


{% if albums %}
    <h2 class="album_line">The albums of {{ artist.alias }}:</h2>
{% endif%}



<div class="albums">
    {% for album in albums %}
    {% if album.name != 'None' %}
    <!-- <a class='song_link' href="{{ song.get_absolute_url }}">
        <img class='song_cover' src="{{ song.cover.url }}" alt="">
        <div class='song'>
            <div class='song_name'>{{ song.name }}</div>
            
        </div> -->
        
        <div class='album'>
            <a class='album_link' href="{{ album.get_absolute_url }}">
                <img class='album_cover' src="{{ album.cover.url }}" alt="">
                <span class='album_name'>{{ album.name }}</span>
            </a> 
        </div> 
    {% endif %}    
    {% endfor %}
</div>

{% endblock %}

musicsite/lemni/templates/lemni/artists_list.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}Artists{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/artists_list.css'%}">{% endblock %}
{% block content %}
<div class='artists_list'>
    <h1 class='title'>Artists</h1>
    <!-- <input type="text" placeholder="Search..."> -->
    {% for artist in artists %}
        {% if artist.alias != 'None' %}
        <div class='artist'>
            <a class='artist-link' href="{{ artist.get_absolute_url }}">
                <img class='photo' src="{{ artist.photo.url }}" alt="">
                
                <span class='artist-alias'>{{ artist.alias }}</span>
            </a> 
        </div>
        {% endif %}
        
        <!-- <div class='artist-alias'>{{ artist.alias }}</div> -->
    
    

    {% endfor %}
</div>

{% endblock %}

musicsite/lemni/templates/lemni/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <!-- <link type="text/css" href="/dist/skin/pink.flag/css/jplayer.pink.flag.css" rel="stylesheet" /> -->
    <!-- <script type="text/javascript" src="/musicsite/jPlayer/dist/jplayer/jquery.min.js"></script> -->
    <!-- <script type="text/javascript" src="/../../../jPlayer/dist/jplayer/jquery.jplayer.min.js"></script> -->
<!-- <script type="text/javascript" src="/home/alex//Desktop/Lemni/musicsite/jPlayer/dist/jplayer/jquery.jplayer.min.js"></script> -->
    
    <meta charset="UTF-8">
    <meta name="description" content="Music site of Lemniscata">
    <meta name="keywords" content="music, artists, songs, clips">
    <meta name="robots" content="nofollow">
    <meta http-equiv="autor" content="Alex Suzen">
    <meta http-equiv="pragma" content="no-cache">
    <title>{% block title %}LeMusic{% endblock %}</title> <!--Change to Lemusic -->
    <link rel="stylesheet" href="{% static 'css/base1.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fontawesome.com/icons/telegram?style=brands">
    {% block extra_css %}{% endblock %}
</head>
<body>
<div class='wrapper'>
        <div>
            <span class='header-left'>
                <a class = 'main_link' href="{% url 'lemni:main' %}">
                    <span class='header-text'>LeMusic</span>
                </a>
            </span>
    
            <span class='header-right'>
                <a href="{% url 'lemni:artists_list' %}" class='Artists'>Artists</a>
                <a href="{% url 'lemni:songs_list' %}" class='Songs'>Songs</a>
                <a href="{% url 'lemni:albums_list' %}" class='Albums'>Albums</a>
                <a href="{% url 'lemni:clips_list' %}" class='Clips'>Clips</a>
                
                <div class="wrapper-btn">
                    {% if user.is_authenticated%}
                        <a class='profile' href="{% url 'lemni:profile' %}"><span class='prof_link'>Hi, {{ user.username }}!</span></a>
                        <a class="Log_out" href="{% url 'lemni:logout' %}">Log out</a>
                    {% else %}
                        <a href="{% url 'lemni:registration' %}" class='Sign_up'>Sign up</a>
                        <a href="{% url 'lemni:login' %}" class='Log_in'>Log in</a>
                    {% endif%}
                </div>
                
            </span>
        <div>
    {% block content %}
    <div class='margin-bg'>
        <div class="body1">
            <div class='quote'>“Music comes to me more readily than words.”   <span class='bet'>Ludwig Van Beethoven</span></div>
            <div class='pic'><img src="{% static 'imgs/bet.jpg'%}" alt="" class="bet_pic"></div>
            <!-- <img src="{% static 'imgs/bet.jpg'%}}" alt=""> -->
        </div>
    </div>
    
    <!-- <div>
        <h2>Some text</h2>
    </div> -->
    <div class="my_message">Hi, I'm Alex and I'm 21. There you can see something that I've tried to create.</div>
    {% endblock %}
    <div class="push"></div>
</div>
<footer class='footer'>
    <a href="{% url 'lemni:artists_list' %}" class='Artists'>Artists</a>
    <a href="{% url 'lemni:songs_list' %}" class='Songs'>Songs</a>
    <a href="{% url 'lemni:albums_list' %}" class='Albums'>Albums</a>
    <a href="{% url 'lemni:clips_list' %}" class='Clips'>Clips</a>
    <div class="social">
        <a href="#"><img src="{% static 'social/Linkedin.svg'%}" alt=""></a>
        <a href="https://t.me/asuzen" target="_blank"><img src="{% static 'social/Telegram.svg'%}" alt=""></a> 
        <!-- <a href="#"><img src="media/social/facebook.svg" alt=""></a> -->
        <a href="#"><img src="{% static 'social/facebook.svg'%}" alt=""></a>
    </div> 
    <div class='reference'>
        <span>Lemniscata, 2021</span>
    </div>
</footer>
</body>
</html>

musicsite/lemni/templates/lemni/clips_list.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}Clips{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/clips_list.css'%}"> {% endblock %}
{% block content %}
<div class='clips_list'>
    <h1>Dope clips</h1>
    {% for clip in clips %}
    <div class='item-clip'>
        <!-- <a href="{{ clip.link }}" class="clip"></a> -->
        <!-- <iframe width="560" height="315" src="{{ clip.link }}" frameborder="0"></iframe> -->
        <!-- <div>{{ clip.link }}</div> -->
        <h2 class='clip_title'>{{ clip.title }}</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ clip.link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <!-- <span>{{ clip.title }}</span> -->

    </div>
    {% endfor %}
</div>
{% endblock %}

musicsite/lemni/templates/lemni/song_detail.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}{{ song.name }}{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/song_detail.css'%}">{% endblock %}
{% block content %}
    <div class="item">
        <img src="{{ song.cover.url }}" alt="" class="cover">
        <div class="description">
            <h1 class="name"><span class='label'>Name: </span>{{ song.name }}</h1>
            <div class="artist"><span class='label'>Artist: </span><a href='{{ artist.get_absolute_url }}'>{{ artist }}</a></div>
            <div class="feature"><span class='label'>Feature: </span><a href='{% url "lemni:artist_detail" slug="blackbear"  %}'>{% for feature in features %} {{feature}} {% endfor %}</a></div>
            <div class="release_date"><span class='label'>Release date: </span> {{ song.release_date }}</div>
            <div class="genres"><span class='label'>Genres: </span>{% for genre in genres %} {{ genre }} {% endfor %}</div>
            <div class="info"><span class='label'>Info: </span> {{ song.description }}</div>
            <a href="{{ song.lyrics }}" class="lyrics" target="_blank">Check lyrics</a>

           
        </div>
    </div>
{% endblock %}

musicsite/lemni/templates/lemni/songs_list.html
{% extends 'lemni/base.html' %}
{% load static %}
{% block title %}Songs{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/songs_list.css'%}">{% endblock %}
{% block content %}
<div class='songs_list'>
    <h1>Songs</h1>
    {% for song in songs %}
        <!-- <h3>{{ song.name }}</h3> -->
        <div class='song'>
            <a class='song_link' href="{{ song.get_absolute_url }}">
                <img class='song_cover' src="{{ song.cover.url }}" alt="">
                <!-- <span class='song_name'>{{ song.name }}</span> -->

                <div class='song_name'>{{ song.name }} <br></div>
                <!-- <div class='song_name'>{{ song.name }}</div> -->
            </a> 
        </div> 
       
    {% endfor %}
</div>
{% endblock %}